name: Unit Tests

on:
  push:
    branches: [ "develop", "staging" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 6.0.x

      - name: Restore Dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --no-restore --configuration Release

      - name: Run Tests
        run: dotnet test ${{ github.workspace }}/SoftUniBazar.Tests/SoftUniBazar.Tests.csproj --no-build --verbosity normal
